name: gulp

on:
  push:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install&gulp
      run: |
        npm i gulp gulp-terser gulp-minify-css -D && npx gulp
        gulp 
        
    - name: Commit
      run: |
        ls
        rm -rf node_modules
        git config --global user.email chen2778754364@foxmail.com
        git config --global user.name ChenYFan
        git add . 
        git commit -m ":zap: 已压缩" -a
        
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist
        FOLDER: /dist
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
