name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: CLEANTEMP
      run: |
        curl https://purge.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@latest/update.js
        curl https://purge.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@latest/index.js  
